### ISSUE TITLE
not working in BalloonEditor

### ISSUE THREAD

**Issue by c0deheld** [ckeditor/ckeditor5-alignment#34]
Using the standard ballooneditor sample, the Alignment plugin causes the toolbar to show below the editing content instead on top of it.

**Comment by Mgsy** [comment]
Could you provide some screenshot, so we'll be able to see your issue?

**Comment by c0deheld** [comment]
As it should be:

![should](https://user-images.githubusercontent.com/47591433/54212833-b8311480-44e3-11e9-807c-a21e2a0dd2ef.png)

As it is:

![is](https://user-images.githubusercontent.com/47591433/54212838-ba936e80-44e3-11e9-88f2-ea84850ed89f.png)


The only difference I have is this in ckeditor.js:

`import Alignment from '@ckeditor/ckeditor5-alignment/src/alignment';`

I'm not even adding it to the builtinPlugins.

**Comment by c0deheld** [comment]
As it should be: 
![should](https://user-images.githubusercontent.com/47591433/54213178-473e2c80-44e4-11e9-83b3-99e21bd96542.png)

As it is: 
![is](https://user-images.githubusercontent.com/47591433/54213182-49a08680-44e4-11e9-9f1b-c8e3171b06df.png)


The only thing I add to ckeditor.js is:

`import Alignment from '@ckeditor/ckeditor5-alignment/src/alignment';`

**Comment by Mgsy** [comment]
Thanks for the screenshot. Are you sure that all your dependencies are updated? You can check it i.e. with [npm-check-updates](https://www.npmjs.com/package/npm-check-updates).

**Comment by c0deheld** [comment]
I updated all dependencies but get the same result.

**Comment by Mgsy** [comment]
Okay, thanks. Could you share exact steps what are you doing from scratch, so we'll be able to check whether we can reproduce your issue?

**Comment by Mgsy** [comment]
I'm closing it due to a lack of activity.
