### ISSUE TITLE
not working with InlineEditor 

### ISSUE THREAD

**Issue by jdtwlodar** [ckeditor/ckeditor5-alignment#35]
adding ckeditor5-alignment plugin does not work correctly with @ ckeditor / ckeditor5-editor-inline / src / inlineeditor ' 
Box with tools gets position: static; and does not work with top and left positioning.

**Comment by Mgsy** [comment]
Hello, did you see our [installing plugins guide](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/installing-plugins.html)? Does this problem still exists after following steps from the guide?

**Comment by jdtwlodar** [comment]
Problem starts when I add
import Alignment from '@ckeditor/ckeditor5-alignment/src/alignment';

**Comment by Mgsy** [comment]
Could you share with us your project, so we can take a look and see what might be wrong?

**Comment by jdtwlodar** [comment]
I can't share my cod, but
my temporary solution is overwrite class 
```
.ck.ck-balloon-panel {
  position: absolute!important;
}
```

**Comment by Mgsy** [comment]
Thanks for the information. So, could you write exact steps for how to reproduce this issue? We'd like to know the cause of this problem. Any additional info would be appreciated.

Another question - are you able to reproduce this issue just for CKEditor 5 (without integration with your project)? Maybe there is some styling collision between the editor and your styles?

**Comment by Mgsy** [comment]
I'm closing it due to a lack of activity.
