### ISSUE TITLE
The requested toolbar item is unavailable.

### ISSUE THREAD

**Issue by MansoorJafari** [ckeditor/ckeditor5-alignment#39]
I'm using this code for set alignment to toolbar (Angular 7)

 public Editor = ClassicEditor;
     public config = {
            toolbar: [ 'heading', '|', 'bold', 'italic','|','bulletedList', 'numberedList', 'undo', 'redo','alignment' ],
     }

but give me this warning and not working

ckeditor.js:5 toolbarview-item-unavailable: The requested toolbar item is unavailable. Read more: https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/error-codes.html#error-toolbarview-item-unavailable
 {name: "alignment"}

this is my ckeditor in html 

`  
     <ckeditor [config]="config"  [editor]="Editor" ></ckeditor>
`

**Comment by Mgsy** [comment]
Hello, your problem occurs because your build doesn't contain the alignment plugin. Please, take a look at our [installing plugins guide](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/installing-plugins.html).
