### ISSUE TITLE
Change attribute conversion in model to view conversions

### ISSUE THREAD

**Issue by jodator** [ckeditor/ckeditor5-alignment#5]
Conversion to style attribute (only used by Alignment feature ATM) would overwrite other (or will by overwritten by others) if any other feature would like to convert model `attribute` to `style` attribute.

Upcoming changes in https://github.com/ckeditor/ckeditor5-engine/issues/1172 should introduce a better helper for this.

**Comment by jodator** [comment]
So the issue is addressed by the help of @szymonkups in #2. I'm leaving this ticket to remember about this when referenced ticket will be closed.

**Comment by szymonkups** [comment]
Closed by https://github.com/ckeditor/ckeditor5-alignment/pull/6.
